name: Publish Hazelcast Management Center packages

on:
  push:
    # Push to master updates the latest snapshot (MC_VERSION taken from pom.xml)
    branches:
      - master
    # Push of a matching tag (v*, e.g. v5.0.2) starts build with
    # - HZ_VERSION extracted from pom.xml
    # - PACKAGE_VERSION extracted from the tag
    tags:
      - 'v*'
  pull_request:
    types: [ opened, synchronize, edited ]
  workflow_dispatch:
    inputs:
      MC_VERSION:
        description: 'Version of Hazelcast Management Center to build the image for, this is the Maven version - e.g.: 5.0.2 or 5.1-SNAPSHOT'
        required: true

env:
  EVENT_NAME: ${{ github.event_name }}

# Constant for now - should ensure single build, maybe we can limit this to something from github.*
concurrency: single-build

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '8' ]
        architecture: [ 'x64' ]
    env:
      MC_VERSION: ${{ github.event.inputs.MC_VERSION }}
      PUBLISH: "true"
      ARTIFACTORY_SECRET: ${{ secrets.ARTIFACTORY_SECRET }}
      DEVOPS_PRIVATE_KEY: ${{ secrets.DEVOPS_PRIVATE_KEY }}
      BINTRAY_PASSPHRASE: ${{ secrets.BINTRAY_PASSPHRASE }}
    defaults:
      run:
        working-directory: ./hazelcast-command-line
    outputs:
      mc_version: ${{ steps.hz_version.outputs.mc_version }}
      package_version: ${{ steps.package_version.outputs.package_version }}
    name: Release Automation
    steps:
      - name: Checkout hazelcast-command-line repo
        uses: actions/checkout@v2.3.2
        with:
          path: 'hazelcast-command-line'

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}

      - name: Set MC_VERSION
        id: mc_version
        run: |
          if [ -z "${{ env.MC_VERSION }}" ]; then
            MC_VERSION=$(mvn help:evaluate -Dexpression=hazelcast.mc.version -q -DforceStdout)
          fi
          echo "MC_VERSION=$MC_VERSION" >> $GITHUB_ENV
          echo ::set-output name=mc_version::$HZ_VERSION

      - name: Set PACKAGE_VERSION
        id: package_version
        # If the ref is version (e.g. v5.0.1) tag then use it as package version,
        # otherwise use HZ_VERSION for package version (e.g 5.1-SNAPSHOT)
        run: |
          if [[ "${{ github.ref }}" == "v"* ]]; then
            PACKAGE_VERSION=$(echo ${{ github.ref }} | cut -c 12-)
          else
            PACKAGE_VERSION=${{ env.MC_VERSION }}
          fi
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo ::set-output name=package_version::$PACKAGE_VERSION

      - name: Download the distribution tar.gz file
        run: |          
          if [[ "${MC_VERSION}" != *SNAPSHOT* ]]; then
            VERSION="${MC_VERSION}"
          else
            VERSION=latest-snapshot
          fi
          HZ_PACKAGE_URL="https://repository.hazelcast.com/download/management-center/hazelcast-management-center-${MC_VERSION}.tar.gz"
          echo "HZ_PACKAGE_URL=$HZ_PACKAGE_URL" >> $GITHUB_ENV

      - name: Create & Upload DEB package
        run: |
          ./build-mc-deb-package.sh

      - name: Create & Sign & Upload RPM package
        run: |
#          ./build-rpm-package.sh

      - name: Get homebrew repository
        run: |
          source ./common.sh
          echo "BREW_GIT_REPO_NAME=${BREW_GIT_REPO_NAME}" >> $GITHUB_ENV

      - name: Checkout homebrew-hz repo
        uses: actions/checkout@v2.3.1
        with:
          repository: ${{ env.BREW_GIT_REPO_NAME }}
          ref: master
          token: ${{ secrets.DEVOPS_SECRET }}
          path: 'homebrew-hz'

      - name: Change the artifact in homebrew-hz
        run: |
          ./build-mc-homebrew-package.sh

      - name: Commit changes & Push to homebrew-hz repo
        run: |
          source common.sh
          
          cd ../homebrew-hz
          git config --global user.name 'devOpsHazelcast'
          git config --global user.email 'devops@hazelcast.com'
          git add Aliases
          git add hazelcast-management-center@${BREW_PACKAGE_VERSION}.rb
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            git commit -am "Hazelcast Management Center ${{ env.PACKAGE_VERSION }} release"
            git pull --rebase
            git push
          else
            echo "No changes, this is probably a re-run."
          fi

  update-deb:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Calculate Debian Repository Metadata
        run: |
          source common.sh

          curl -H "Authorization: Bearer ${{ secrets.ARTIFACTORY_SECRET }}" \
            -X POST "https://repository.hazelcast.com/api/deb/reindex/${DEBIAN_REPO}"

  update-rpm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Calculate YUM Repository Metadata
        run: |
          source common.sh

          curl -H "Authorization: Bearer ${{ secrets.ARTIFACTORY_SECRET }}" \
            -X POST "https://repository.hazelcast.com/api/yum/${RPM_REPO}"

  verify-deb:
    runs-on: ubuntu-latest
    env:
      MC_VERSION: ${{ needs.build.outputs.mc_version }}
      PACKAGE_VERSION: ${{ needs.build.outputs.package_version }}
      HZ_LICENSEKEY: ${{ secrets.HZ_LICENSEKEY }}
    needs: [ build, update-deb, update-rpm ]
    name: Hazelcast Management Center DEB Package Verification
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Install Hazelcast Management Center from DEB
        run: |
          source ./common.sh
          wget -qO - https://repository.hazelcast.com/api/gpg/key/public | sudo apt-key add -
          echo "deb ${DEBIAN_REPO_BASE_URL} ${PACKAGE_REPO} main" | sudo tee -a /etc/apt/sources.list
          sudo apt update && sudo apt install hazelcast-management-center=${{ env.PACKAGE_VERSION }}
          JAVA_OPTS="-Dhazelcast.mc.healthCheck.enable=true"
          ls /usr/lib/hazelcast/
          ls /usr/lib/hazelcast-management-center
          /usr/lib/hazelcast/hazelcast-management-center-${MC_VERSION}/bin/start.s > hz-mc.log 2>&1 &

      - name: Check Hazelcast Management Center Health
        run: |
          ./check-hazelcast-health.sh

      - name: Uninstall CLI from deb
        run: |
          source ./common.sh
          sudo apt remove hazelcast-management-center

#  verify-rpm:
#    runs-on: ubuntu-latest
#    container: centos:latest
#    env:
#      MC_VERSION: ${{ needs.build.outputs.MC_version }}
#      PACKAGE_VERSION: ${{ needs.build.outputs.package_version }}
#      HZ_LICENSEKEY: ${{ secrets.HZ_LICENSEKEY }}
#    needs: [ build, update-deb, update-rpm ]
#    name: MC RPM Package Verification
#    steps:
#      - uses: actions/checkout@v2.3.2
#
#      - name: Install MC from RPM
#        run: |
#          source ./common.sh
#          yum install -y wget
#          wget ${RPM_REPO_BASE_URL}/${PACKAGE_REPO}/hazelcast-rpm-${PACKAGE_REPO}.repo -O hazelcast-rpm-${PACKAGE_REPO}.repo
#          mv hazelcast-rpm-${PACKAGE_REPO}.repo /etc/yum.repos.d/
#          yum install -y ${{ env.HZ_DISTRIBUTION}}-${RPM_PACKAGE_VERSION}
#          HAZELCAST_CONFIG="${GITHUB_WORKSPACE}/config/integration-test-hazelcast.yaml" hz-start > hz.log 2>&1 &
#
#      - name: Check MC health
#        run: |
#          ./check-hazelcast-health.sh
#
#      - name: Uninstall CLI from rpm
#        run: |
#          source ./common.sh
#          yum remove -y ${{ env.HZ_DISTRIBUTION}}-${RPM_PACKAGE_VERSION}

  verify-homebrew:
    runs-on: macos-latest
    env:
      MC_VERSION: ${{ needs.build.outputs.MC_version }}
      PACKAGE_VERSION: ${{ needs.build.outputs.package_version }}
      HZ_LICENSEKEY: ${{ secrets.HZ_LICENSEKEY }}
    needs: [ build, update-deb, update-rpm ]
    name: Hazelcast Management Center Homebrew Package Verification
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Install Hazelcast Management Center from Homebrew
        run: |
          source ./common.sh
          brew tap ${BREW_TAP_NAME}
          brew install hazelcast-management-center@$BREW_PACKAGE_VERSION

      - name: Run Hazelcast Management Center
        run: |
          export JAVA_OPTS="-Dhazelcast.mc.healthCheck.enable=true" 
          /usr/local/opt/hazelcast@$BREW_PACKAGE_VERSION/libexec/bin/start.sh > hz-mc.log 2>&1 &

      - name: Check Hazelcast Management Center Health
        run: |
          ./check-mc-health.sh

      - name: Uninstall Hazelcast Management Center from Homebrew
        run: |
          source ./common.sh          
          brew uninstall hazelcast-management-center@$BREW_PACKAGE_VERSION
